-- Stain the Canvas - Analisis de clientes anonimo (sin PII)
-- Run in Supabase SQL Editor.
-- Este script NO guarda datos personales (nombre, correo, telefono, direccion).
-- Se centra en sesion anonima + eventos de comportamiento para medir embudo hacia WhatsApp.

create extension if not exists pgcrypto;
create schema if not exists private;

-- Catalogo de fuentes de trafico (normalizado)
create table if not exists public.fuentes_trafico (
  id smallint generated by default as identity primary key,
  codigo text not null unique,
  nombre text not null,
  created_at timestamptz not null default now()
);

-- Catalogo de tipos de evento (normalizado)
create table if not exists public.tipos_evento_cliente (
  id smallint generated by default as identity primary key,
  codigo text not null unique,
  descripcion text,
  created_at timestamptz not null default now()
);

-- Sesiones anonimas (cliente no identificado)
create table if not exists public.sesiones_cliente_anonimas (
  id uuid primary key default gen_random_uuid(),
  session_id text not null unique,
  fuente_id smallint references public.fuentes_trafico(id) on delete set null,
  landing_path text,
  user_agent text,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

-- Eventos anonimos por sesion
create table if not exists public.eventos_cliente_anonimos (
  id uuid primary key default gen_random_uuid(),
  sesion_id uuid not null references public.sesiones_cliente_anonimas(id) on delete cascade,
  tipo_evento_id smallint not null references public.tipos_evento_cliente(id) on delete restrict,
  producto_id uuid references public.productos(id) on delete set null,
  categoria text,
  meta jsonb not null default '{}'::jsonb,
  fecha timestamptz not null default now()
);

create index if not exists idx_fuentes_trafico_codigo on public.fuentes_trafico (codigo);
create index if not exists idx_tipos_evento_cliente_codigo on public.tipos_evento_cliente (codigo);
create index if not exists idx_sesiones_cliente_anonimas_session_id on public.sesiones_cliente_anonimas (session_id);
create index if not exists idx_sesiones_cliente_anonimas_first_seen on public.sesiones_cliente_anonimas (first_seen_at desc);
create index if not exists idx_sesiones_cliente_anonimas_last_seen on public.sesiones_cliente_anonimas (last_seen_at desc);
create index if not exists idx_eventos_cliente_anonimos_sesion_id on public.eventos_cliente_anonimos (sesion_id);
create index if not exists idx_eventos_cliente_anonimos_tipo_fecha on public.eventos_cliente_anonimos (tipo_evento_id, fecha desc);
create index if not exists idx_eventos_cliente_anonimos_producto_id on public.eventos_cliente_anonimos (producto_id);
create index if not exists idx_eventos_cliente_anonimos_categoria on public.eventos_cliente_anonimos (categoria);

-- Seed basico para fuentes y tipos
insert into public.fuentes_trafico (codigo, nombre)
values
  ('directo', 'Directo'),
  ('instagram', 'Instagram'),
  ('facebook', 'Facebook'),
  ('whatsapp', 'WhatsApp'),
  ('referido', 'Referido'),
  ('otro', 'Otro')
on conflict (codigo) do nothing;

insert into public.tipos_evento_cliente (codigo, descripcion)
values
  ('view_producto', 'Visualizacion de producto'),
  ('click_whatsapp', 'Clic al boton de WhatsApp')
on conflict (codigo) do nothing;

-- Reutiliza helper admin si ya existe en setup.sql
create or replace function public.is_admin_user()
returns boolean
language sql
stable
as $$
  select
    lower(coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '')) = 'admin'
    or lower(coalesce(auth.jwt() -> 'app_metadata' ->> 'is_admin', 'false')) = 'true'
    or exists (
      select 1
      from public.admin_users au
      where au.user_id = auth.uid()
        and au.is_active = true
    );
$$;

alter table public.fuentes_trafico enable row level security;
alter table public.tipos_evento_cliente enable row level security;
alter table public.sesiones_cliente_anonimas enable row level security;
alter table public.eventos_cliente_anonimos enable row level security;

-- Lectura administrativa

drop policy if exists "Admins can read fuentes trafico" on public.fuentes_trafico;
create policy "Admins can read fuentes trafico"
on public.fuentes_trafico
for select
using (public.is_admin_user());

drop policy if exists "Admins can read tipos evento cliente" on public.tipos_evento_cliente;
create policy "Admins can read tipos evento cliente"
on public.tipos_evento_cliente
for select
using (public.is_admin_user());

drop policy if exists "Admins can read sesiones cliente anonimas" on public.sesiones_cliente_anonimas;
create policy "Admins can read sesiones cliente anonimas"
on public.sesiones_cliente_anonimas
for select
using (public.is_admin_user());

drop policy if exists "Admins can read eventos cliente anonimos" on public.eventos_cliente_anonimos;
create policy "Admins can read eventos cliente anonimos"
on public.eventos_cliente_anonimos
for select
using (public.is_admin_user());

-- Insercion publica controlada (sin datos personales)

drop policy if exists "Public can insert sesiones cliente anonimas" on public.sesiones_cliente_anonimas;
create policy "Public can insert sesiones cliente anonimas"
on public.sesiones_cliente_anonimas
for insert
with check (
  char_length(trim(coalesce(session_id, ''))) between 16 and 128
  and char_length(coalesce(user_agent, '')) <= 500
  and char_length(coalesce(landing_path, '')) <= 300
);

drop policy if exists "Public can insert eventos cliente anonimos" on public.eventos_cliente_anonimos;
create policy "Public can insert eventos cliente anonimos"
on public.eventos_cliente_anonimos
for insert
with check (
  tipo_evento_id is not null
  and char_length(coalesce(categoria, '')) <= 80
);

-- Gestion administrativa completa

drop policy if exists "Admins can manage fuentes trafico" on public.fuentes_trafico;
create policy "Admins can manage fuentes trafico"
on public.fuentes_trafico
for all
using (public.is_admin_user())
with check (public.is_admin_user());

drop policy if exists "Admins can manage tipos evento cliente" on public.tipos_evento_cliente;
create policy "Admins can manage tipos evento cliente"
on public.tipos_evento_cliente
for all
using (public.is_admin_user())
with check (public.is_admin_user());

drop policy if exists "Admins can manage sesiones cliente anonimas" on public.sesiones_cliente_anonimas;
create policy "Admins can manage sesiones cliente anonimas"
on public.sesiones_cliente_anonimas
for all
using (public.is_admin_user())
with check (public.is_admin_user());

drop policy if exists "Admins can manage eventos cliente anonimos" on public.eventos_cliente_anonimos;
create policy "Admins can manage eventos cliente anonimos"
on public.eventos_cliente_anonimos
for all
using (public.is_admin_user())
with check (public.is_admin_user());

-- Trigger: al registrar evento, actualiza last_seen_at de la sesion
create or replace function private.touch_sesion_last_seen()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  update public.sesiones_cliente_anonimas
  set last_seen_at = greatest(last_seen_at, new.fecha)
  where id = new.sesion_id;

  return new;
end;
$$;

revoke all on function private.touch_sesion_last_seen() from public;

drop trigger if exists trg_touch_sesion_last_seen on public.eventos_cliente_anonimos;
create trigger trg_touch_sesion_last_seen
after insert on public.eventos_cliente_anonimos
for each row execute function private.touch_sesion_last_seen();

-- Trigger: evita spam de eventos duplicados por sesion
create or replace function public.guard_eventos_cliente_anonimos_insert()
returns trigger
language plpgsql
as $$
begin
  if exists (
    select 1
    from public.eventos_cliente_anonimos e
    where e.sesion_id = new.sesion_id
      and e.tipo_evento_id = new.tipo_evento_id
      and coalesce(e.producto_id::text, '') = coalesce(new.producto_id::text, '')
      and e.fecha > now() - interval '8 seconds'
  ) then
    return null;
  end if;

  if (
    select count(*)
    from public.eventos_cliente_anonimos e
    where e.sesion_id = new.sesion_id
      and e.fecha > now() - interval '1 minute'
  ) >= 60 then
    return null;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_guard_eventos_cliente_anonimos_insert on public.eventos_cliente_anonimos;
create trigger trg_guard_eventos_cliente_anonimos_insert
before insert on public.eventos_cliente_anonimos
for each row execute function public.guard_eventos_cliente_anonimos_insert();

-- RPC para tracking anonimo desde frontend
-- Garantiza sesion + evento sin exponer PII.
create or replace function public.track_evento_cliente_anonimo(
  p_session_id text,
  p_tipo_evento_codigo text,
  p_producto_id uuid default null,
  p_categoria text default null,
  p_user_agent text default null,
  p_fuente_codigo text default 'directo',
  p_landing_path text default null,
  p_meta jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_session_id text;
  v_fuente_id smallint;
  v_tipo_evento_id smallint;
  v_sesion_uuid uuid;
begin
  v_session_id := trim(coalesce(p_session_id, ''));
  if char_length(v_session_id) < 16 or char_length(v_session_id) > 128 then
    raise exception 'session_id invalido';
  end if;

  select id into v_fuente_id
  from public.fuentes_trafico
  where codigo = lower(coalesce(trim(p_fuente_codigo), 'directo'))
  limit 1;

  if v_fuente_id is null then
    select id into v_fuente_id
    from public.fuentes_trafico
    where codigo = 'otro'
    limit 1;
  end if;

  select id into v_tipo_evento_id
  from public.tipos_evento_cliente
  where codigo = lower(coalesce(trim(p_tipo_evento_codigo), ''))
  limit 1;

  if v_tipo_evento_id is null then
    raise exception 'tipo_evento no permitido';
  end if;

  insert into public.sesiones_cliente_anonimas (session_id, fuente_id, landing_path, user_agent)
  values (
    v_session_id,
    v_fuente_id,
    nullif(left(coalesce(p_landing_path, ''), 300), ''),
    nullif(left(coalesce(p_user_agent, ''), 500), '')
  )
  on conflict (session_id)
  do update set
    fuente_id = coalesce(public.sesiones_cliente_anonimas.fuente_id, excluded.fuente_id),
    landing_path = coalesce(public.sesiones_cliente_anonimas.landing_path, excluded.landing_path),
    user_agent = coalesce(public.sesiones_cliente_anonimas.user_agent, excluded.user_agent),
    last_seen_at = now()
  returning id into v_sesion_uuid;

  insert into public.eventos_cliente_anonimos (
    sesion_id,
    tipo_evento_id,
    producto_id,
    categoria,
    meta,
    fecha
  )
  values (
    v_sesion_uuid,
    v_tipo_evento_id,
    p_producto_id,
    nullif(left(coalesce(p_categoria, ''), 80), ''),
    coalesce(p_meta, '{}'::jsonb),
    now()
  );
end;
$$;

revoke all on function public.track_evento_cliente_anonimo(text, text, uuid, text, text, text, text, jsonb) from public;
grant execute on function public.track_evento_cliente_anonimo(text, text, uuid, text, text, text, text, jsonb) to anon, authenticated;

-- RPC dedicada al dashboard de analisis anonimo de clientes
create or replace function public.get_clientes_anon_dashboard_metrics(p_days integer default 90)
returns jsonb
language sql
stable
as $$
with params as (
  select greatest(1, least(coalesce(p_days, 90), 3650)) as days
),
cutoff as (
  select now() - make_interval(days => (select days from params)) as ts
),
sesiones_src as (
  select s.*
  from public.sesiones_cliente_anonimas s
  where s.first_seen_at >= (select ts from cutoff)
     or s.last_seen_at >= (select ts from cutoff)
),
eventos_src as (
  select e.*, te.codigo as tipo_codigo
  from public.eventos_cliente_anonimos e
  join public.tipos_evento_cliente te on te.id = e.tipo_evento_id
  where e.fecha >= (select ts from cutoff)
),
sesiones_por_dia as (
  select
    to_char(date_trunc('day', s.first_seen_at), 'YYYY-MM-DD') as day,
    count(*)::int as total
  from sesiones_src s
  group by 1
  order by 1
),
by_fuente as (
  select
    coalesce(f.nombre, 'Sin fuente') as fuente,
    count(*)::int as total
  from sesiones_src s
  left join public.fuentes_trafico f on f.id = s.fuente_id
  group by 1
  order by total desc
),
top_productos as (
  select
    e.producto_id,
    coalesce(p.nombre, concat('Producto ', left(e.producto_id::text, 8))) as nombre,
    coalesce(nullif(p.categoria, ''), nullif(e.categoria, ''), 'Sin categoria') as categoria,
    count(*)::int as vistas
  from eventos_src e
  left join public.productos p on p.id = e.producto_id
  where e.tipo_codigo = 'view_producto'
    and e.producto_id is not null
  group by e.producto_id, nombre, categoria
  order by vistas desc
  limit 10
),
by_categoria as (
  select
    coalesce(nullif(p.categoria, ''), nullif(e.categoria, ''), 'Sin categoria') as categoria,
    count(*)::int as total
  from eventos_src e
  left join public.productos p on p.id = e.producto_id
  where e.tipo_codigo = 'view_producto'
  group by 1
  order by total desc
),
totals as (
  select
    (select count(*)::int from sesiones_src) as total_sesiones,
    (select count(*)::int from eventos_src where tipo_codigo = 'view_producto') as total_vistas_producto,
    (select count(*)::int from eventos_src where tipo_codigo = 'click_whatsapp') as total_clicks_whatsapp
)
select jsonb_build_object(
  'totals', jsonb_build_object(
    'totalSesiones', coalesce((select total_sesiones from totals), 0),
    'totalVistasProducto', coalesce((select total_vistas_producto from totals), 0),
    'totalClicksWhatsapp', coalesce((select total_clicks_whatsapp from totals), 0),
    'conversionWhatsapp', case
      when coalesce((select total_vistas_producto from totals), 0) > 0
        then round(((select total_clicks_whatsapp from totals)::numeric / (select total_vistas_producto from totals)::numeric) * 100, 1)
      else 0
    end
  ),
  'sessionsSeries', coalesce(
    (select jsonb_agg(jsonb_build_object('day', day, 'total', total) order by day) from sesiones_por_dia),
    '[]'::jsonb
  ),
  'bySource', coalesce(
    (select jsonb_agg(jsonb_build_object('fuente', fuente, 'total', total) order by total desc) from by_fuente),
    '[]'::jsonb
  ),
  'topProducts', coalesce(
    (
      select jsonb_agg(
        jsonb_build_object(
          'id', producto_id,
          'nombre', nombre,
          'categoria', categoria,
          'vistas', vistas
        )
        order by vistas desc
      )
      from top_productos
    ),
    '[]'::jsonb
  ),
  'byCategory', coalesce(
    (
      select jsonb_agg(
        jsonb_build_object('categoria', categoria, 'total', total)
        order by total desc
      )
      from by_categoria
    ),
    '[]'::jsonb
  )
);
$$;

-- Consultas de verificacion:
-- select public.track_evento_cliente_anonimo(
--   p_session_id => 'stc-1234567890abcdef',
--   p_tipo_evento_codigo => 'view_producto',
--   p_producto_id => null,
--   p_categoria => 'Pinturas',
--   p_user_agent => 'Mozilla/5.0',
--   p_fuente_codigo => 'instagram',
--   p_landing_path => '/catalogo.html',
--   p_meta => '{"from":"home"}'::jsonb
-- );
--
-- select public.get_clientes_anon_dashboard_metrics(90);
