-- Stain the Canvas - Supabase setup
-- Run in Supabase SQL Editor.
-- Security model:
-- - Public read for catalog browsing.
-- - Admin write for admin actions (app_metadata.role='admin' or app_metadata.is_admin=true).
-- - Public insert for analytics events (visitas/eventos).

create extension if not exists pgcrypto;

create table if not exists public.productos (
  id uuid primary key default gen_random_uuid(),
  nombre text not null,
  categoria text not null,
  descripcion text not null,
  precio numeric(10,2) not null default 0 check (precio >= 0),
  imagen_url text,
  gallery_urls jsonb not null default '[]'::jsonb,
  vistas integer not null default 0,
  clicks integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.productos
  add column if not exists gallery_urls jsonb not null default '[]'::jsonb,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists vistas integer not null default 0,
  add column if not exists clicks integer not null default 0;

update public.productos
set gallery_urls =
  case
    when coalesce(trim(imagen_url), '') <> '' then jsonb_build_array(imagen_url)
    else '[]'::jsonb
  end
where gallery_urls is null
   or jsonb_typeof(gallery_urls) <> 'array'
   or gallery_urls = '[]'::jsonb;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_productos_updated_at on public.productos;
create trigger trg_productos_updated_at
before update on public.productos
for each row execute function public.set_updated_at();

create table if not exists public.visitas (
  id uuid primary key default gen_random_uuid(),
  fecha timestamptz not null default now(),
  session_id text not null,
  user_agent text
);

create table if not exists public.eventos (
  id uuid primary key default gen_random_uuid(),
  tipo text not null,
  producto_id uuid references public.productos(id) on delete set null,
  categoria text,
  session_id text not null,
  fecha timestamptz not null default now()
);

create table if not exists public.admin_users (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique,
  email text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists idx_visitas_fecha on public.visitas (fecha desc);
create index if not exists idx_visitas_session_id on public.visitas (session_id);
create index if not exists idx_eventos_tipo_fecha on public.eventos (tipo, fecha desc);
create index if not exists idx_eventos_producto_id on public.eventos (producto_id);
create index if not exists idx_eventos_categoria on public.eventos (categoria);

alter table public.productos enable row level security;
alter table public.visitas enable row level security;
alter table public.eventos enable row level security;
alter table public.admin_users enable row level security;

create or replace function public.is_admin_user()
returns boolean
language sql
stable
as $$
  select
    lower(coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '')) = 'admin'
    or lower(coalesce(auth.jwt() -> 'app_metadata' ->> 'is_admin', 'false')) = 'true'
    or exists (
      select 1
      from public.admin_users au
      where au.user_id = auth.uid()
        and au.is_active = true
    );
$$;

drop policy if exists "Admins can read own membership" on public.admin_users;
create policy "Admins can read own membership"
on public.admin_users
for select
using (auth.uid() = user_id);

drop policy if exists "Public can read productos" on public.productos;
create policy "Public can read productos"
on public.productos
for select
using (true);

drop policy if exists "Public can insert productos" on public.productos;
drop policy if exists "Authenticated can insert productos" on public.productos;
create policy "Authenticated can insert productos"
on public.productos
for insert
with check (
  public.is_admin_user()
);

drop policy if exists "Public can update productos" on public.productos;
drop policy if exists "Authenticated can update productos" on public.productos;
create policy "Authenticated can update productos"
on public.productos
for update
using (
  public.is_admin_user()
)
with check (
  public.is_admin_user()
);

drop policy if exists "Public can delete productos" on public.productos;
drop policy if exists "Authenticated can delete productos" on public.productos;
create policy "Authenticated can delete productos"
on public.productos
for delete
using (
  public.is_admin_user()
);

drop policy if exists "Public can insert visitas" on public.visitas;
create policy "Public can insert visitas"
on public.visitas
for insert
with check (
  char_length(trim(coalesce(session_id, ''))) between 16 and 128
  and char_length(coalesce(user_agent, '')) <= 500
);

drop policy if exists "Authenticated can read visitas" on public.visitas;
create policy "Authenticated can read visitas"
on public.visitas
for select
using (
  public.is_admin_user()
);

drop policy if exists "Public can insert eventos" on public.eventos;
create policy "Public can insert eventos"
on public.eventos
for insert
with check (
  tipo in ('view_producto', 'click_whatsapp')
  and char_length(trim(coalesce(session_id, ''))) between 16 and 128
  and char_length(coalesce(categoria, '')) <= 80
);

drop policy if exists "Authenticated can read eventos" on public.eventos;
create policy "Authenticated can read eventos"
on public.eventos
for select
using (
  public.is_admin_user()
);

insert into storage.buckets (id, name, public)
values ('productos', 'productos', true)
on conflict (id) do update set public = excluded.public;

drop policy if exists "Public can view product images" on storage.objects;
create policy "Public can view product images"
on storage.objects
for select
using (bucket_id = 'productos');

drop policy if exists "Public can upload product images" on storage.objects;
drop policy if exists "Authenticated can upload product images" on storage.objects;
create policy "Authenticated can upload product images"
on storage.objects
for insert
with check (
  bucket_id = 'productos'
  and (
    public.is_admin_user()
  )
);

drop policy if exists "Public can update product images" on storage.objects;
drop policy if exists "Authenticated can update product images" on storage.objects;
create policy "Authenticated can update product images"
on storage.objects
for update
using (
  bucket_id = 'productos'
  and (
    public.is_admin_user()
  )
)
with check (
  bucket_id = 'productos'
  and (
    public.is_admin_user()
  )
);

drop policy if exists "Public can delete product images" on storage.objects;
drop policy if exists "Authenticated can delete product images" on storage.objects;
create policy "Authenticated can delete product images"
on storage.objects
for delete
using (
  bucket_id = 'productos'
  and (
    public.is_admin_user()
  )
);

create or replace function public.guard_visitas_insert()
returns trigger
language plpgsql
as $$
begin
  if exists (
    select 1
    from public.visitas v
    where v.session_id = new.session_id
      and v.fecha > now() - interval '15 seconds'
  ) then
    return null;
  end if;

  if (
    select count(*)
    from public.visitas v
    where v.session_id = new.session_id
      and v.fecha > now() - interval '1 minute'
  ) >= 30 then
    return null;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_guard_visitas_insert on public.visitas;
create trigger trg_guard_visitas_insert
before insert on public.visitas
for each row execute function public.guard_visitas_insert();

create or replace function public.guard_eventos_insert()
returns trigger
language plpgsql
as $$
begin
  if exists (
    select 1
    from public.eventos e
    where e.session_id = new.session_id
      and e.tipo = new.tipo
      and coalesce(e.producto_id::text, '') = coalesce(new.producto_id::text, '')
      and e.fecha > now() - interval '8 seconds'
  ) then
    return null;
  end if;

  if (
    select count(*)
    from public.eventos e
    where e.session_id = new.session_id
      and e.fecha > now() - interval '1 minute'
  ) >= 60 then
    return null;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_guard_eventos_insert on public.eventos;
create trigger trg_guard_eventos_insert
before insert on public.eventos
for each row execute function public.guard_eventos_insert();

create or replace function public.get_dashboard_metrics(p_days integer default 90)
returns jsonb
language sql
stable
as $$
with params as (
  select greatest(1, least(coalesce(p_days, 90), 3650)) as days
),
cutoff as (
  select now() - make_interval(days => (select days from params)) as ts
),
visitas_src as (
  select fecha
  from public.visitas v
  where v.fecha >= (select ts from cutoff)
),
eventos_src as (
  select tipo, producto_id, categoria, fecha
  from public.eventos e
  where e.fecha >= (select ts from cutoff)
),
totales as (
  select
    (select count(*) from visitas_src) as total_visitas,
    (select count(*) from eventos_src where tipo = 'view_producto') as total_vistas,
    (select count(*) from eventos_src where tipo = 'click_whatsapp') as total_clicks
),
visitas_serie as (
  select
    to_char(date_trunc('day', fecha), 'YYYY-MM-DD') as day,
    count(*)::int as total
  from visitas_src
  group by 1
  order by 1
),
top_productos as (
  select
    es.producto_id,
    coalesce(p.nombre, concat('Producto ', left(es.producto_id::text, 8))) as nombre,
    coalesce(nullif(p.categoria, ''), nullif(es.categoria, ''), 'Sin categoria') as categoria,
    count(*)::int as vistas
  from eventos_src es
  left join public.productos p on p.id = es.producto_id
  where es.tipo = 'view_producto'
    and es.producto_id is not null
  group by es.producto_id, nombre, categoria
  order by vistas desc
  limit 10
),
categorias as (
  select
    coalesce(nullif(p.categoria, ''), nullif(es.categoria, ''), 'Sin categoria') as categoria,
    count(*)::int as total
  from eventos_src es
  left join public.productos p on p.id = es.producto_id
  where es.tipo = 'view_producto'
  group by 1
  order by total desc
)
select jsonb_build_object(
  'totals', jsonb_build_object(
    'totalVisitas', coalesce((select total_visitas from totales), 0),
    'totalVistas', coalesce((select total_vistas from totales), 0),
    'totalClicks', coalesce((select total_clicks from totales), 0),
    'conversion', case
      when coalesce((select total_vistas from totales), 0) > 0
        then round(((select total_clicks from totales)::numeric / (select total_vistas from totales)::numeric) * 100, 1)
      else 0
    end
  ),
  'visitSeries', coalesce(
    (select jsonb_agg(jsonb_build_object('day', day, 'total', total) order by day) from visitas_serie),
    '[]'::jsonb
  ),
  'topProducts', coalesce(
    (
      select jsonb_agg(
        jsonb_build_object(
          'id', producto_id,
          'nombre', nombre,
          'categoria', categoria,
          'vistas', vistas
        )
        order by vistas desc
      )
      from top_productos
    ),
    '[]'::jsonb
  ),
  'byCategory', coalesce(
    (
      select jsonb_agg(
        jsonb_build_object(
          'categoria', categoria,
          'total', total
        )
        order by total desc
      )
      from categorias
    ),
    '[]'::jsonb
  )
);
$$;
